name: Publish to TestPyPI and PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    outputs:
      dist-folder: ${{ steps.build.outputs.dist-folder }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel setuptools-scm build

      - name: Build package
        id: build
        run: |
          python -m build
        outputs:
          dist-folder: dist

      - name: Upload package to GitHub artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  testpypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download package from build job
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: testpypi  # Only run after TestPyPI succeeds
    steps:
      - name: Download package from build job
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
